# (PART) Digital Data Collection {-}


#### Learning Objectives

- Understand how to collect ForestPlots data using Excel on a tablet


## Set up your computer {.unnumbered}

In order to collect data on your tablet via excel, you need two things: 

1. To stay organised and  
2. Excel  

Once you have those, you are ready to prepare your field sheets.


## Preparing field sheets {.unnumbered}

Preparing field sheets to collect data on a tablet is very similar to preparing regular field sheets. In fact, the first steps are the same: download a field sheet from ForestPlots and format it so that you can see only the columns that you want to be able to work with.

The next step is slightly different. Rather than set your print area, now you are going to lock columns that you do not want to accidentally modify in the field.

(insert instructions and necessary images to show how to lock columns)


## Upload the field sheet to the tablet

(insert instructions)

## Collect data on the tablet

(insert instructions)

## Upload the collected data to a computer

(insert instructions)


## Activity 1: Digital Data Collection via Excel

**1.** Create a folder for the course.

**2.** Download the pre-prepared field sheet on your laptop (insert link here later).

**3.** Move the field sheet from your laptop onto your tablet.

**4.** Disconnect the laptop and the tablet and fill in the field sheet.

**5.** Save the filld in field sheet on your computer.

*Discussion: how was the experience? What potential errors can you see?*


## Activity 2: Preparing field sheets

In your group create your own locked excel sheet and decide which columns you believe are required for field work.

*Discussion: Compare group field sheets. What are the similarities and the differences among field sheets?*


## Activity 3: Recommended format

Based on ForestPlots protocol and our experience, (attach example locked field sheet). And discuss.

Potentially a second page for this below...
D.	What does this look like in the field? Charging, protocol after the field work, …