# (PART) Digital Data Collection {-}

# Data Collection via Excel

#### Learning Objectives {-}

- Understand how to collect ForestPlots data using Excel on a tablet


## Set up your computer {.unnumbered}

In order to collect data on your tablet via excel, you need two things: 

1. To stay organised and  
2. Excel  

Hopefully, you have already configured this in `Module 2 and 3`. If you have not set up your devices, return to the section `Setting up your devices`. 

If you already have Excel on your tablet and laptop, then you are ready to prepare your field sheets.


## Preparing field sheets on ForestPlots {.unnumbered}

If you already know how to prepare field sheets through the ForestPlots database, skip ahead to the next section. 

If you need a refresher on how to create field sheets, watch [this video](https://www.youtube.com/watch?v=1Tkdu_Vgilk&feature=youtu.be) or visit page 174 of the [ForestPlots Manual](https://forestplots.net/upload/ManualsEnglish/ForestPlotsManual_2019_sm.pdf).

If you've never been shown how to make field sheets before by a ForestPlots team member, reach out to the data officer of the country that you will be collecting data in and request training *(see Module 2)*.


## Preparing field sheets for the tablet {.unnumbered}

Preparing field sheets to collect data on a tablet is very similar to preparing regular field sheets. In fact, the first step is the same: 
- download a field sheet from ForestPlots,  
- and format the field sheet to only see the columns that you want to work with.  

The next step is slightly different. Rather than set your print area, now you are going to lock columns that you do not want to accidentally modify in the field.

(**ELIOTT** insert instructions and necessary images to show how to lock columns)


## Upload the field sheet to the tablet {-}
(**ELIOTT**  insert instructions)


## Collect data on the tablet {-}
(**ELIOTT**  insert instructions)


## Upload the collected data to a computer {-}
(**ELIOTT**  insert instructions)


## Activity 1: Digital Data Collection via Excel {-}

**1.** Create a folder for the course.  

**2.** Download the pre-prepared field sheet on your laptop (insert link here later).  

**3.** Move the field sheet from your laptop onto your tablet.  

**4.** Disconnect the laptop and the tablet and fill in the field sheet.  

**5.** Save the filled in field sheet on your computer.  

*Discussion: how was the experience? What potential errors can you see?*


## Activity 2: Preparing field sheets {-}

In your group create your own locked excel field sheet and decide which columns you believe are required for field work.

*Discussion: Compare group field sheets. What are the similarities and the differences among field sheets?*


## Activity 3: Recommended format {-}

Based on ForestPlots protocol and our experience, (attach example locked field sheet). And discuss.

**ELIOTT** to add information to this section.

Potentially a second page for this below...
D.	What does this look like in the field? Charging, protocol after the field work, …